#
# URL settings
#
# these need to be adjusted depending on target platform,
# local Jekyll tests need different settings than github-pages :-(


# "real" deployment with github-pages but custom domain
# -----------------------------------------------------
url: https://faq.arc42.org
imageurl: https://faq.arc42.org
baseurl:
#######################################################

## imageurl set to url + baseurl, easier than the complex
## {{ url }}{{ url }}{{ '<filename>' | prepend: site.baseurl }}
#imageurl: http://arc42.github.io/faq




#
# basic settings
#
title: arc42 FAQ
description: frequently asked questions on arc42.
avatar: /assets/img/arc42logosquare.png
favicon: /assets/img/arc42logosquare.png
language: en


#
# want subtle ads (on post-pages)
#
show-subtle-ads: true


# Analytics
analytics: false

#
# Icons
#
icons:
  rss: false
  email: false
  github: arc42
  twitter: gernotstarke
  google_plus: 
  stack_overflow: arc42

#
# Prettify url.
#
permalink: pretty


#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent answers
str_show_all_posts: Show all questions/answers

#
# Gems.
#
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages", "robots.txt"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - _manage-site.sh
  - _docker*
  - README.md
  - originals/

